version: "3"

services:
  web:
    image: nginx:1.23.0
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./kuizy:/var/www/html
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./kuizy:/var/www/html
  db:
    image: mysql:8.0.30
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=posse
    ports:
      - 3306:3306
